# Generated by Django 3.2.3 on 2021-07-05 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210624_1358'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='self_introduction',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='自己紹介'),
        ),
    ]
