# Generated by Django 3.2.3 on 2021-06-17 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tube', '0002_auto_20210523_1747'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='mime',
        ),
    ]
