# Generated by Django 3.2.3 on 2021-06-25 05:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tube', '0003_remove_video_mime'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='badvideo',
            field=models.ManyToManyField(blank=True, related_name='_tube_video_badvideo_+', through='tube.BadVideo', to='tube.Video', verbose_name='バッド評価'),
        ),
        migrations.AddField(
            model_name='video',
            name='goodvideo',
            field=models.ManyToManyField(blank=True, related_name='_tube_video_goodvideo_+', through='tube.GoodVideo', to='tube.Video', verbose_name='グッド評価'),
        ),
        migrations.AlterField(
            model_name='badvideo',
            name='target',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bad_target', to='tube.video', verbose_name='対象動画'),
        ),
        migrations.AlterField(
            model_name='badvideo',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bad_user', to='tube.video', verbose_name='低評価したユーザー'),
        ),
        migrations.AlterField(
            model_name='goodvideo',
            name='target',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='good_target', to='tube.video', verbose_name='対象動画'),
        ),
        migrations.AlterField(
            model_name='goodvideo',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='good_user', to='tube.video', verbose_name='高評価したユーザー'),
        ),
    ]
