# Generated by Django 3.2.3 on 2021-06-25 05:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tube', '0004_auto_20210625_1416'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='badvideo',
        ),
        migrations.RemoveField(
            model_name='video',
            name='goodvideo',
        ),
        migrations.AlterField(
            model_name='badvideo',
            name='target',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tube.video', verbose_name='対象動画'),
        ),
        migrations.AlterField(
            model_name='badvideo',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='低評価したユーザー'),
        ),
        migrations.AlterField(
            model_name='goodvideo',
            name='target',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tube.video', verbose_name='対象動画'),
        ),
        migrations.AlterField(
            model_name='goodvideo',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='高評価したユーザー'),
        ),
    ]
